'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.225
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sniper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1295813182_Internet_Explorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1295813182_Internet-Explorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1295814102_satelite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1295814102_satelite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1295814102_satelite1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1295814102_satelite1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1295815212_quick_restart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1295815212_quick_restart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1295815739_old_go_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1295815739_old-go-top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499042_Control_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499042_Control-Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499092_fileclose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499092_fileclose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499123_mycomputer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499123_mycomputer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499257_application_x_desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499257_application-x-desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499257_application_x_desktop1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499257_application-x-desktop1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499311_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499311_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499332_button_blue_repeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499332_button_blue_repeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499354_Windows_Log_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499354_Windows_Log_Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499579_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499579_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296499579_info1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296499579_info1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296671525_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296671525_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1296847899_Connections() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1296847899_Connections", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1297106147_Play1Hot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1297106147_Play1Hot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1297454786_gnutella() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1297454786_gnutella", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1297459169_xine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1297459169_xine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1297459224_Symbol_Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1297459224_Symbol-Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1297459329_remote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1297459329_remote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1298063917_resize_diag_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1298063917_resize diag 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1298063983_backup_restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1298063983_backup-restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1298149176_progressbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1298149176_progressbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1298924187_interact() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1298924187_interact", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299525427_file_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299525427_file_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299525627_Folder_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299525627_Folder-Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299528532_Rename() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299528532_Rename", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299528532_Rename1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299528532_Rename1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299698298_start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299698298_start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299698356_icontexto_aurora_folders_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299698356_icontexto-aurora-folders-open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299702441_editcopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299702441_editcopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299702464_edit_paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299702464_edit-paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299786608_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299786608_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299786608_101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299786608_101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1299786658_parcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1299786658_parcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300106901_312() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300106901_312", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300106901_3121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300106901_3121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300106901_3122() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300106901_3122", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300106922_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300106922_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300106922_close1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300106922_close1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300126724_notebook_boy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300126724_notebook_boy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300126724_notebook_boy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300126724_notebook_boy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300127056_3floppy_unmount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300127056_3floppy_unmount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300127122_3floppy_unmount() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300127122_3floppy_unmount", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300127188_edit_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300127188_edit-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1300362518_Circle_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1300362518_Circle_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301338949_screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301338949_screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301605304_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301605304_Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301605477_Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301605477_Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301605492_alert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301605492_alert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301605515_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301605515_Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301605515_Help1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301605515_Help1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1301605527_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1301605527_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1302375075_webcam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1302375075_webcam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1302375075_webcam1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1302375075_webcam1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1303247350_tick_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1303247350_tick_circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306238974_preferences_desktop_keyboard_shortcuts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306238974_preferences-desktop-keyboard-shortcuts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306254106_player_rec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306254106_player_rec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306254272_Stop1NormalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306254272_Stop1NormalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306255534_audacity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306255534_audacity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306589090_Applications() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306589090_Applications", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306589186_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306589186_book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1306589281_edit_clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1306589281_edit-clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307280197_sound_mute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1307280197_sound_mute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307280225_contrast_decrease() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1307280225_contrast_decrease", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307280249_increase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1307280249_increase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1307457878_tester() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1307457878_tester", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1308057262_monotone_arrow_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1308057262_monotone_arrow_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _478_radar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("478-radar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property countdown() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("countdown", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mirino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mirino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sniper_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sniper Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
